version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    platform: linux/amd64
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "SLUonTOP123"
    ports:
      - "1433:1433"
    volumes:
      - sqldata:/var/opt/mssql
      - ./database/setup.sql:/setup.sql

  flask:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DB_SERVER=db
      - DB_PASSWORD=SLUonTOP123

volumes:
  sqldata:
